// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CursorPos lưu vị trí con trỏ trong editor.
 */
export class CursorPos {
    "line": number;
    "column": number;

    /** Creates a new CursorPos instance. */
    constructor($$source: Partial<CursorPos> = {}) {
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            this["column"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CursorPos instance from a string or object.
     */
    static createFrom($$source: any = {}): CursorPos {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CursorPos($$parsedSource as Partial<CursorPos>);
    }
}

/**
 * QueryTab đại diện cho một tab query trong editor.
 */
export class QueryTab {
    "id": string;
    "connectionId": string;
    "title": string;
    "content": string;
    "filePath": string | null;
    "isDirty": boolean;
    "cursorPos": CursorPos;
    "createdAt": number;
    "order": number;

    /** Creates a new QueryTab instance. */
    constructor($$source: Partial<QueryTab> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = null;
        }
        if (!("isDirty" in $$source)) {
            this["isDirty"] = false;
        }
        if (!("cursorPos" in $$source)) {
            this["cursorPos"] = (new CursorPos());
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("order" in $$source)) {
            this["order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryTab instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryTab {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cursorPos" in $$parsedSource) {
            $$parsedSource["cursorPos"] = $$createField6_0($$parsedSource["cursorPos"]);
        }
        return new QueryTab($$parsedSource as Partial<QueryTab>);
    }
}

/**
 * WorkspaceSession là snapshot toàn bộ workspace của một connection.
 */
export class WorkspaceSession {
    "activeConnectionId": string;
    "activeTabId": string;
    "tabs": QueryTab[];
    "lastSavedAt": number;

    /** Creates a new WorkspaceSession instance. */
    constructor($$source: Partial<WorkspaceSession> = {}) {
        if (!("activeConnectionId" in $$source)) {
            this["activeConnectionId"] = "";
        }
        if (!("activeTabId" in $$source)) {
            this["activeTabId"] = "";
        }
        if (!("tabs" in $$source)) {
            this["tabs"] = [];
        }
        if (!("lastSavedAt" in $$source)) {
            this["lastSavedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceSession instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceSession {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tabs" in $$parsedSource) {
            $$parsedSource["tabs"] = $$createField2_0($$parsedSource["tabs"]);
        }
        return new WorkspaceSession($$parsedSource as Partial<WorkspaceSession>);
    }
}

// Private type creation functions
const $$createType0 = CursorPos.createFrom;
const $$createType1 = QueryTab.createFrom;
const $$createType2 = $Create.Array($$createType1);
