// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnectionConfig holds a connection's metadata. EncryptedPassword is a
 * base64-encoded blob of (nonce || AES-256-GCM ciphertext+tag).
 */
export class ConnectionConfig {
    "id": string;
    "name": string;
    "driver": string;
    "host": string;
    "port": number;
    "user": string;
    "dbname": string;
    "encrypted_password": string;

    /** Creates a new ConnectionConfig instance. */
    constructor($$source: Partial<ConnectionConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("dbname" in $$source)) {
            this["dbname"] = "";
        }
        if (!("encrypted_password" in $$source)) {
            this["encrypted_password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionConfig($$parsedSource as Partial<ConnectionConfig>);
    }
}

/**
 * Profile — mirror của db.Profile, tách riêng để store không import db
 */
export class Profile {
    "id": string;
    "name": string;
    "driver": string;
    "host": string;
    "port": number;
    "user": string;
    "password": string;
    "database": string;
    "sslMode": string;
    "tag": Tag;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("sslMode" in $$source)) {
            this["sslMode"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = (new Tag());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tag" in $$parsedSource) {
            $$parsedSource["tag"] = $$createField9_0($$parsedSource["tag"]);
        }
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

/**
 * Tag gắn nhãn màu cho một profile kết nối.
 */
export class Tag {
    "name": string;

    /**
     * hex color, e.g. "#3B82F6"
     */
    "color": string;

    /** Creates a new Tag instance. */
    constructor($$source: Partial<Tag> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     */
    static createFrom($$source: any = {}): Tag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tag($$parsedSource as Partial<Tag>);
    }
}

// Private type creation functions
const $$createType0 = Tag.createFrom;
