package mysql

import "github.com/thtn-dev/table_stack/internal/db"

// GetDialectInfo returns static MySQL dialect metadata used by the frontend
// SQL completion engine. Data is hardcoded and never requires a DB round-trip.
// The returned pointer must not be modified by callers.
func (d *Driver) GetDialectInfo() *db.DialectInfo {
	return &db.DialectInfo{
		ProviderType: "mysql",
		Keywords:     mysqlKeywords,
		Functions:    mysqlFunctions,
		DataTypes:    mysqlDataTypes,
		Operators:    mysqlOperators,
	}
}

var mysqlKeywords = []string{
	"SELECT", "FROM", "WHERE", "AND", "OR", "NOT", "IN", "NOT IN",
	"LIKE", "NOT LIKE", "BETWEEN", "IS NULL", "IS NOT NULL",
	"INSERT INTO", "VALUES", "UPDATE", "SET", "DELETE FROM",
	"CREATE TABLE", "ALTER TABLE", "DROP TABLE", "TRUNCATE TABLE",
	"CREATE INDEX", "CREATE UNIQUE INDEX", "DROP INDEX",
	"CREATE VIEW", "DROP VIEW",
	"JOIN", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN",
	"CROSS JOIN", "NATURAL JOIN",
	"GROUP BY", "ORDER BY", "HAVING", "LIMIT", "OFFSET",
	"UNION", "UNION ALL",
	"DISTINCT", "ALL",
	"BEGIN", "COMMIT", "ROLLBACK", "SAVEPOINT",
	"EXPLAIN", "DESCRIBE", "DESC",
	"SHOW TABLES", "SHOW DATABASES", "SHOW COLUMNS FROM",
	"SHOW CREATE TABLE", "SHOW INDEX FROM",
	"USE",
	"ON DUPLICATE KEY UPDATE",
	"AUTO_INCREMENT", "ENGINE", "DEFAULT CHARSET", "COLLATE",
	"CASE", "WHEN", "THEN", "ELSE", "END",
	"CAST", "COALESCE", "IFNULL",
	"ASC", "DESC",
	"PRIMARY KEY", "UNIQUE", "NOT NULL", "DEFAULT", "CHECK", "REFERENCES",
	"CONSTRAINT", "FOREIGN KEY",
	"AS", "ON", "USING",
	"IF EXISTS", "IF NOT EXISTS",
	"REPLACE INTO",
}

var mysqlDataTypes = []string{
	"TINYINT", "SMALLINT", "MEDIUMINT", "INT", "INTEGER", "BIGINT",
	"DECIMAL", "NUMERIC", "FLOAT", "DOUBLE", "DOUBLE PRECISION",
	"VARCHAR", "TEXT", "TINYTEXT", "MEDIUMTEXT", "LONGTEXT",
	"CHAR", "BINARY", "VARBINARY",
	"BLOB", "TINYBLOB", "MEDIUMBLOB", "LONGBLOB",
	"BOOLEAN", "BOOL",
	"DATE", "TIME", "DATETIME", "TIMESTAMP", "YEAR",
	"JSON",
	"ENUM", "SET",
	"BIT",
}

var mysqlOperators = []string{
	"=", "!=", "<>", "<", ">", "<=", ">=", "<=>",
	"DIV", "MOD", "XOR",
	"REGEXP", "NOT REGEXP", "RLIKE",
	"IS DISTINCT FROM", "IS NOT DISTINCT FROM",
}

var mysqlFunctions = []db.FunctionInfo{
	{Name: "NOW", Signature: "NOW()", Description: "Current date and time"},
	{Name: "CURDATE", Signature: "CURDATE()", Description: "Current date"},
	{Name: "CURTIME", Signature: "CURTIME()", Description: "Current time"},
	{Name: "SYSDATE", Signature: "SYSDATE()", Description: "Current date and time at execution time"},
	{Name: "COALESCE", Signature: "COALESCE(val1, val2, ...)", Description: "Return first non-null value"},
	{Name: "IFNULL", Signature: "IFNULL(expr, alt_value)", Description: "Return alt_value if expr is null"},
	{Name: "NULLIF", Signature: "NULLIF(a, b)", Description: "Return null if a = b"},
	{Name: "IF", Signature: "IF(condition, true_val, false_val)", Description: "Conditional expression"},
	{Name: "COUNT", Signature: "COUNT(*) / COUNT(expr)", Description: "Count rows"},
	{Name: "SUM", Signature: "SUM(expr)", Description: "Sum of values"},
	{Name: "AVG", Signature: "AVG(expr)", Description: "Average value"},
	{Name: "MIN", Signature: "MIN(expr)", Description: "Minimum value"},
	{Name: "MAX", Signature: "MAX(expr)", Description: "Maximum value"},
	{Name: "GROUP_CONCAT", Signature: "GROUP_CONCAT([DISTINCT] expr [ORDER BY ...] [SEPARATOR str])", Description: "Concatenate group values into string"},
	{Name: "DATE_FORMAT", Signature: "DATE_FORMAT(date, format)", Description: "Format date using format string"},
	{Name: "DATE_ADD", Signature: "DATE_ADD(date, INTERVAL n unit)", Description: "Add time to date"},
	{Name: "DATE_SUB", Signature: "DATE_SUB(date, INTERVAL n unit)", Description: "Subtract time from date"},
	{Name: "DATEDIFF", Signature: "DATEDIFF(date1, date2)", Description: "Number of days between two dates"},
	{Name: "TIMESTAMPDIFF", Signature: "TIMESTAMPDIFF(unit, datetime1, datetime2)", Description: "Difference between two timestamps"},
	{Name: "UNIX_TIMESTAMP", Signature: "UNIX_TIMESTAMP([date])", Description: "Convert date to Unix timestamp"},
	{Name: "FROM_UNIXTIME", Signature: "FROM_UNIXTIME(timestamp [, format])", Description: "Convert Unix timestamp to date"},
	{Name: "STR_TO_DATE", Signature: "STR_TO_DATE(string, format)", Description: "Parse string into date using format"},
	{Name: "YEAR", Signature: "YEAR(date)", Description: "Extract year from date"},
	{Name: "MONTH", Signature: "MONTH(date)", Description: "Extract month from date"},
	{Name: "DAY", Signature: "DAY(date)", Description: "Extract day from date"},
	{Name: "HOUR", Signature: "HOUR(time)", Description: "Extract hour from time"},
	{Name: "MINUTE", Signature: "MINUTE(time)", Description: "Extract minute from time"},
	{Name: "SECOND", Signature: "SECOND(time)", Description: "Extract second from time"},
	{Name: "CONCAT", Signature: "CONCAT(str1, str2, ...)", Description: "Concatenate strings"},
	{Name: "CONCAT_WS", Signature: "CONCAT_WS(separator, str1, str2, ...)", Description: "Concatenate with separator"},
	{Name: "SUBSTRING", Signature: "SUBSTRING(string, start [, length])", Description: "Extract substring"},
	{Name: "SUBSTR", Signature: "SUBSTR(string, start [, length])", Description: "Extract substring"},
	{Name: "LEFT", Signature: "LEFT(string, length)", Description: "Return leftmost n characters"},
	{Name: "RIGHT", Signature: "RIGHT(string, length)", Description: "Return rightmost n characters"},
	{Name: "TRIM", Signature: "TRIM([LEADING|TRAILING|BOTH] [chars FROM] string)", Description: "Remove characters from ends"},
	{Name: "LTRIM", Signature: "LTRIM(string)", Description: "Remove leading spaces"},
	{Name: "RTRIM", Signature: "RTRIM(string)", Description: "Remove trailing spaces"},
	{Name: "UPPER", Signature: "UPPER(string)", Description: "Convert to uppercase"},
	{Name: "LOWER", Signature: "LOWER(string)", Description: "Convert to lowercase"},
	{Name: "LENGTH", Signature: "LENGTH(string)", Description: "Length in bytes"},
	{Name: "CHAR_LENGTH", Signature: "CHAR_LENGTH(string)", Description: "Length in characters"},
	{Name: "REPLACE", Signature: "REPLACE(string, from, to)", Description: "Replace all occurrences"},
	{Name: "LPAD", Signature: "LPAD(string, length, padstring)", Description: "Pad string on left to length"},
	{Name: "RPAD", Signature: "RPAD(string, length, padstring)", Description: "Pad string on right to length"},
	{Name: "FORMAT", Signature: "FORMAT(number, decimal_places)", Description: "Format number with grouped thousands"},
	{Name: "ROUND", Signature: "ROUND(number [, decimal_places])", Description: "Round to decimal places"},
	{Name: "FLOOR", Signature: "FLOOR(number)", Description: "Largest integer <= number"},
	{Name: "CEIL", Signature: "CEIL(number)", Description: "Smallest integer >= number"},
	{Name: "ABS", Signature: "ABS(number)", Description: "Absolute value"},
	{Name: "MOD", Signature: "MOD(dividend, divisor)", Description: "Remainder after division"},
	{Name: "POWER", Signature: "POWER(base, exponent)", Description: "Raise base to exponent"},
	{Name: "SQRT", Signature: "SQRT(value)", Description: "Square root"},
	{Name: "RAND", Signature: "RAND([seed])", Description: "Random float between 0 and 1"},
	{Name: "CAST", Signature: "CAST(expr AS type)", Description: "Type cast"},
	{Name: "CONVERT", Signature: "CONVERT(expr, type)", Description: "Type conversion"},
	{Name: "LAST_INSERT_ID", Signature: "LAST_INSERT_ID()", Description: "Last auto-generated ID"},
	{Name: "UUID", Signature: "UUID()", Description: "Generate a UUID"},
	{Name: "MD5", Signature: "MD5(string)", Description: "Compute MD5 hash as hex string"},
	{Name: "SHA1", Signature: "SHA1(string)", Description: "Compute SHA-1 hash as hex string"},
	{Name: "SHA2", Signature: "SHA2(string, hash_length)", Description: "Compute SHA-2 family hash"},
	{Name: "JSON_EXTRACT", Signature: "JSON_EXTRACT(json_doc, path, ...)", Description: "Extract value from JSON"},
	{Name: "JSON_OBJECT", Signature: "JSON_OBJECT(key, value, ...)", Description: "Create JSON object"},
	{Name: "JSON_ARRAY", Signature: "JSON_ARRAY(val, ...)", Description: "Create JSON array"},
	{Name: "EXISTS", Signature: "EXISTS(subquery)", Description: "True if subquery returns any rows"},
}
