package postgres

import "github.com/thtn-dev/table_stack/internal/db"

// GetDialectInfo returns static PostgreSQL dialect metadata used by the
// frontend SQL completion engine. Data is hardcoded and never requires a
// DB round-trip. The returned pointer must not be modified by callers.
func (d *Driver) GetDialectInfo() *db.DialectInfo {
	return &db.DialectInfo{
		ProviderType: "postgres",
		Keywords:     postgresKeywords,
		Functions:    postgresFunctions,
		DataTypes:    postgresDataTypes,
		Operators:    postgresOperators,
	}
}

var postgresKeywords = []string{
	"SELECT", "FROM", "WHERE", "AND", "OR", "NOT", "IN", "NOT IN",
	"LIKE", "ILIKE", "SIMILAR TO", "BETWEEN", "IS NULL", "IS NOT NULL",
	"INSERT INTO", "VALUES", "UPDATE", "SET", "DELETE FROM",
	"CREATE TABLE", "ALTER TABLE", "DROP TABLE", "TRUNCATE TABLE",
	"CREATE INDEX", "CREATE UNIQUE INDEX", "DROP INDEX",
	"CREATE VIEW", "DROP VIEW", "CREATE MATERIALIZED VIEW",
	"REFRESH MATERIALIZED VIEW",
	"JOIN", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN",
	"FULL OUTER JOIN", "CROSS JOIN", "NATURAL JOIN",
	"GROUP BY", "ORDER BY", "HAVING", "LIMIT", "OFFSET",
	"UNION", "UNION ALL", "INTERSECT", "EXCEPT",
	"DISTINCT", "DISTINCT ON", "ALL",
	"BEGIN", "COMMIT", "ROLLBACK", "SAVEPOINT", "RELEASE SAVEPOINT",
	"EXPLAIN", "EXPLAIN ANALYZE", "EXPLAIN VERBOSE",
	"WITH", "WITH RECURSIVE",
	"RETURNING", "ON CONFLICT DO NOTHING", "ON CONFLICT DO UPDATE",
	"LATERAL", "TABLESAMPLE",
	"CASE", "WHEN", "THEN", "ELSE", "END",
	"CAST", "COALESCE", "NULLIF",
	"ASC", "DESC", "NULLS FIRST", "NULLS LAST",
	"PRIMARY KEY", "UNIQUE", "NOT NULL", "DEFAULT", "CHECK", "REFERENCES",
	"CONSTRAINT", "FOREIGN KEY",
	"WINDOW", "OVER", "PARTITION BY", "FILTER",
	"AS", "ON", "USING", "AT TIME ZONE",
	"IF EXISTS", "IF NOT EXISTS",
	"VACUUM", "ANALYZE", "REINDEX", "CLUSTER",
	"GRANT", "REVOKE", "TO", "WITH GRANT OPTION",
	"DO", "LANGUAGE",
}

var postgresDataTypes = []string{
	"BIGINT", "INT8", "INT", "INTEGER", "INT4", "SMALLINT", "INT2",
	"DECIMAL", "NUMERIC", "REAL", "FLOAT4", "DOUBLE PRECISION", "FLOAT8",
	"VARCHAR", "CHARACTER VARYING", "TEXT", "CHAR", "CHARACTER",
	"BOOLEAN", "BOOL",
	"DATE", "TIME", "TIMETZ", "TIMESTAMP", "TIMESTAMPTZ",
	"INTERVAL",
	"JSON", "JSONB",
	"UUID",
	"INET", "CIDR", "MACADDR",
	"BYTEA",
	"TSVECTOR", "TSQUERY",
	"POINT", "LINE", "LSEG", "BOX", "PATH", "POLYGON", "CIRCLE",
	"INT4RANGE", "INT8RANGE", "NUMRANGE", "TSRANGE", "TSTZRANGE", "DATERANGE",
	"SERIAL", "BIGSERIAL", "SMALLSERIAL",
	"BIT", "BIT VARYING",
	"MONEY", "OID", "XML", "VOID",
}

var postgresOperators = []string{
	"->", "->>", "#>", "#>>",
	"@>", "<@", "?", "?|", "?&",
	"||", "@@", "@@@",
	"~~", "~~*", "!~~", "!~~*",
	"IS DISTINCT FROM", "IS NOT DISTINCT FROM",
	"&", "|", "#", "~", "<<", ">>",
}

var postgresFunctions = []db.FunctionInfo{
	{Name: "NOW", Signature: "NOW()", Description: "Current date and time (with time zone)"},
	{Name: "CURRENT_DATE", Signature: "CURRENT_DATE", Description: "Current date"},
	{Name: "CURRENT_TIME", Signature: "CURRENT_TIME", Description: "Current time with time zone"},
	{Name: "CURRENT_TIMESTAMP", Signature: "CURRENT_TIMESTAMP", Description: "Current timestamp with time zone"},
	{Name: "COALESCE", Signature: "COALESCE(val1, val2, ...)", Description: "Return first non-null value"},
	{Name: "NULLIF", Signature: "NULLIF(a, b)", Description: "Return null if a = b"},
	{Name: "GREATEST", Signature: "GREATEST(val1, val2, ...)", Description: "Return greatest value"},
	{Name: "LEAST", Signature: "LEAST(val1, val2, ...)", Description: "Return smallest value"},
	{Name: "COUNT", Signature: "COUNT(*) / COUNT(expr)", Description: "Count rows"},
	{Name: "SUM", Signature: "SUM(expr)", Description: "Sum of values"},
	{Name: "AVG", Signature: "AVG(expr)", Description: "Average value"},
	{Name: "MIN", Signature: "MIN(expr)", Description: "Minimum value"},
	{Name: "MAX", Signature: "MAX(expr)", Description: "Maximum value"},
	{Name: "ARRAY_AGG", Signature: "ARRAY_AGG(expr [ORDER BY ...])", Description: "Aggregate values into array"},
	{Name: "STRING_AGG", Signature: "STRING_AGG(expr, delimiter)", Description: "Aggregate strings with delimiter"},
	{Name: "JSON_AGG", Signature: "JSON_AGG(expr)", Description: "Aggregate values into JSON array"},
	{Name: "JSONB_SET", Signature: "JSONB_SET(target, path, new_value [, create_missing])", Description: "Set JSONB value at path"},
	{Name: "JSON_BUILD_OBJECT", Signature: "JSON_BUILD_OBJECT(key, value, ...)", Description: "Build JSON object from key-value pairs"},
	{Name: "JSONB_ARRAY_ELEMENTS", Signature: "JSONB_ARRAY_ELEMENTS(jsonb)", Description: "Expand JSONB array to set of values"},
	{Name: "DATE_TRUNC", Signature: "DATE_TRUNC(field, timestamp)", Description: "Truncate timestamp to specified precision"},
	{Name: "DATE_PART", Signature: "DATE_PART(field, timestamp)", Description: "Extract subfield from date/time"},
	{Name: "EXTRACT", Signature: "EXTRACT(field FROM source)", Description: "Extract subfield from date/time value"},
	{Name: "AGE", Signature: "AGE(timestamp [, timestamp])", Description: "Compute age between two timestamps"},
	{Name: "TO_CHAR", Signature: "TO_CHAR(value, format)", Description: "Convert value to string using format"},
	{Name: "TO_DATE", Signature: "TO_DATE(string, format)", Description: "Convert string to date"},
	{Name: "TO_TIMESTAMP", Signature: "TO_TIMESTAMP(string, format)", Description: "Convert string to timestamp"},
	{Name: "GENERATE_SERIES", Signature: "GENERATE_SERIES(start, stop [, step])", Description: "Generate series of values"},
	{Name: "UNNEST", Signature: "UNNEST(array)", Description: "Expand array to rows"},
	{Name: "ROW_NUMBER", Signature: "ROW_NUMBER() OVER (...)", Description: "Sequential row number within partition"},
	{Name: "RANK", Signature: "RANK() OVER (...)", Description: "Rank within partition with gaps"},
	{Name: "DENSE_RANK", Signature: "DENSE_RANK() OVER (...)", Description: "Rank within partition without gaps"},
	{Name: "LAG", Signature: "LAG(column [, offset [, default]]) OVER (...)", Description: "Access previous row value"},
	{Name: "LEAD", Signature: "LEAD(column [, offset [, default]]) OVER (...)", Description: "Access next row value"},
	{Name: "FIRST_VALUE", Signature: "FIRST_VALUE(column) OVER (...)", Description: "First value in window frame"},
	{Name: "LAST_VALUE", Signature: "LAST_VALUE(column) OVER (...)", Description: "Last value in window frame"},
	{Name: "NTILE", Signature: "NTILE(n) OVER (...)", Description: "Bucket rows into n groups"},
	{Name: "PERCENT_RANK", Signature: "PERCENT_RANK() OVER (...)", Description: "Relative rank as fraction"},
	{Name: "CUME_DIST", Signature: "CUME_DIST() OVER (...)", Description: "Cumulative distribution"},
	{Name: "CONCAT", Signature: "CONCAT(str1, str2, ...)", Description: "Concatenate strings"},
	{Name: "CONCAT_WS", Signature: "CONCAT_WS(sep, str1, str2, ...)", Description: "Concatenate with separator"},
	{Name: "SPLIT_PART", Signature: "SPLIT_PART(string, delimiter, field)", Description: "Return nth field from split string"},
	{Name: "TRIM", Signature: "TRIM([LEADING|TRAILING|BOTH] [chars FROM] string)", Description: "Remove characters from ends"},
	{Name: "LTRIM", Signature: "LTRIM(string [, chars])", Description: "Remove leading characters"},
	{Name: "RTRIM", Signature: "RTRIM(string [, chars])", Description: "Remove trailing characters"},
	{Name: "UPPER", Signature: "UPPER(string)", Description: "Convert to uppercase"},
	{Name: "LOWER", Signature: "LOWER(string)", Description: "Convert to lowercase"},
	{Name: "LENGTH", Signature: "LENGTH(string)", Description: "Length of string in characters"},
	{Name: "SUBSTRING", Signature: "SUBSTRING(string FROM start [FOR length])", Description: "Extract substring"},
	{Name: "REPLACE", Signature: "REPLACE(string, from, to)", Description: "Replace all occurrences in string"},
	{Name: "REGEXP_REPLACE", Signature: "REGEXP_REPLACE(string, pattern, replacement [, flags])", Description: "Replace by regex pattern"},
	{Name: "REGEXP_MATCH", Signature: "REGEXP_MATCH(string, pattern [, flags])", Description: "Match string against regex"},
	{Name: "INITCAP", Signature: "INITCAP(string)", Description: "Capitalise first letter of each word"},
	{Name: "LPAD", Signature: "LPAD(string, length [, fill])", Description: "Pad string on left to length"},
	{Name: "RPAD", Signature: "RPAD(string, length [, fill])", Description: "Pad string on right to length"},
	{Name: "MD5", Signature: "MD5(string)", Description: "Compute MD5 hash as hex string"},
	{Name: "ABS", Signature: "ABS(value)", Description: "Absolute value"},
	{Name: "CEIL", Signature: "CEIL(value)", Description: "Smallest integer >= value"},
	{Name: "FLOOR", Signature: "FLOOR(value)", Description: "Largest integer <= value"},
	{Name: "ROUND", Signature: "ROUND(value [, scale])", Description: "Round to specified decimal places"},
	{Name: "TRUNC", Signature: "TRUNC(value [, scale])", Description: "Truncate to specified decimal places"},
	{Name: "POWER", Signature: "POWER(base, exponent)", Description: "Raise base to exponent"},
	{Name: "SQRT", Signature: "SQRT(value)", Description: "Square root"},
	{Name: "RANDOM", Signature: "RANDOM()", Description: "Random float between 0 and 1"},
	{Name: "PG_TYPEOF", Signature: "PG_TYPEOF(value)", Description: "Data type of expression as regtype"},
	{Name: "CAST", Signature: "CAST(expr AS type)", Description: "Type cast"},
	{Name: "TO_JSONB", Signature: "TO_JSONB(value)", Description: "Convert value to JSONB"},
	{Name: "JSONB_PRETTY", Signature: "JSONB_PRETTY(jsonb)", Description: "Format JSONB as indented string"},
	{Name: "EXISTS", Signature: "EXISTS(subquery)", Description: "True if subquery returns any rows"},
}
