// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App exposes backend methods to the frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./internal/db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "./internal/session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

export function ActiveConnections(): $CancellablePromise<string[]> {
    return $Call.ByID(3783369028).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Connect opens a live connection for profileID, retrieving the decrypted
 * password from the CredentialManager.
 */
export function Connect(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(164877153, profileID);
}

/**
 * DeleteConnection removes the ConnectionConfig for connectionID.
 */
export function DeleteConnection(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(3428926502, connectionID);
}

/**
 * DeleteProfile removes the profile and its stored credential.
 */
export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(2457157279, id);
}

export function DescribeTable(profileID: string, schema: string, table: string): $CancellablePromise<db$0.ColumnInfo[]> {
    return $Call.ByID(3867090276, profileID, schema, table).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Disconnect(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(3864343059, profileID);
}

export function ExecuteQuery(profileID: string, sqlStr: string): $CancellablePromise<db$0.QueryResult | null> {
    return $Call.ByID(2868660388, profileID, sqlStr).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetConnectionPassword decrypts and returns the stored password for
 * connectionID. The plaintext is only transmitted over the local IPC bridge.
 */
export function GetConnectionPassword(connectionID: string): $CancellablePromise<string> {
    return $Call.ByID(1106561582, connectionID);
}

/**
 * GetLastActiveProfile returns the profile ID selected last across windows.
 */
export function GetLastActiveProfile(): $CancellablePromise<string> {
    return $Call.ByID(1787524770);
}

/**
 * GetLastConnection reads the last saved connection ID. Returns "" if no
 * connection has been saved yet.
 */
export function GetLastConnection(): $CancellablePromise<string> {
    return $Call.ByID(3478381799);
}

export function IsConnected(profileID: string): $CancellablePromise<boolean> {
    return $Call.ByID(236330520, profileID);
}

/**
 * ListConnections returns all stored ConnectionConfigs with passwords omitted.
 */
export function ListConnections(): $CancellablePromise<store$0.ConnectionConfig[]> {
    return $Call.ByID(786053378).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListDatabases(profileID: string): $CancellablePromise<db$0.DatabaseInfo[]> {
    return $Call.ByID(4238628917, profileID).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListIndexes(profileID: string, schema: string, table: string): $CancellablePromise<db$0.IndexInfo[]> {
    return $Call.ByID(3383199879, profileID, schema, table).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListProfiles returns all profiles with passwords masked.
 */
export function ListProfiles(): $CancellablePromise<store$0.Profile[]> {
    return $Call.ByID(1957526603).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ListSchemas(profileID: string): $CancellablePromise<string[]> {
    return $Call.ByID(3091363483, profileID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListTables(profileID: string, schema: string): $CancellablePromise<db$0.TableInfo[]> {
    return $Call.ByID(364749488, profileID, schema).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * LoadSession loads the workspace session for connID from disk.
 * Returns a default session (1 empty tab) if no saved session exists.
 */
export function LoadSession(connID: string): $CancellablePromise<session$0.WorkspaceSession | null> {
    return $Call.ByID(2280082259, connID).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * OpenFile shows a file open dialog filtered to .sql files.
 * Returns a new QueryTab populated with the file content.
 * Returns nil, nil if the user cancels the dialog.
 */
export function OpenFile(): $CancellablePromise<session$0.QueryTab | null> {
    return $Call.ByID(1958968983).then(($result: any) => {
        return $$createType18($result);
    });
}

export function RegisteredDrivers(): $CancellablePromise<string[]> {
    return $Call.ByID(3935134584).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveConnection stores a ConnectionConfig with an AES-256-GCM encrypted
 * password in the local JSON file. Use this when managing connections
 * independently of the Profile system.
 */
export function SaveConnection(cfg: store$0.ConnectionConfig, plainPassword: string): $CancellablePromise<void> {
    return $Call.ByID(865625064, cfg, plainPassword);
}

/**
 * SaveFile writes the tab content to disk. If tab.FilePath is set, saves in
 * place; otherwise opens a Save As dialog. Returns the updated tab with
 * FilePath, Title, and IsDirty updated, or nil, nil if the user cancels.
 */
export function SaveFile(tab: session$0.QueryTab): $CancellablePromise<session$0.QueryTab | null> {
    return $Call.ByID(1396636678, tab).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * SaveLastConnection writes connID to last_connection.txt so the app can
 * restore the last used connection on next launch.
 */
export function SaveLastConnection(connID: string): $CancellablePromise<void> {
    return $Call.ByID(134231192, connID);
}

/**
 * SaveProfile persists profile metadata and encrypts the password via the
 * OS-keychain-backed CredentialManager. The plaintext password is never
 * written to profiles.json.
 */
export function SaveProfile(p: store$0.Profile): $CancellablePromise<store$0.Profile> {
    return $Call.ByID(406053493, p).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * SaveSession persists the workspace session for connID to disk.
 * The frontend calls this with a debounce of 2s after any state change.
 */
export function SaveSession(connID: string, sess: session$0.WorkspaceSession): $CancellablePromise<void> {
    return $Call.ByID(1031450332, connID, sess);
}

/**
 * SetLastActiveProfile stores the profile that should be focused by the main window.
 */
export function SetLastActiveProfile(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(3037183246, profileID);
}

/**
 * ShowMainWindow asks the host process to create/focus the main window.
 */
export function ShowMainWindow(): $CancellablePromise<void> {
    return $Call.ByID(3189675457);
}

/**
 * TestConnection tests connectivity. If the caller omits or masks the password,
 * the stored credential is fetched automatically.
 */
export function TestConnection(p: store$0.Profile): $CancellablePromise<db$0.ConnectResult> {
    return $Call.ByID(1257240193, p).then(($result: any) => {
        return $$createType19($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = db$0.ColumnInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = db$0.QueryResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = store$0.ConnectionConfig.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = db$0.DatabaseInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = db$0.IndexInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = store$0.Profile.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = db$0.TableInfo.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = session$0.WorkspaceSession.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = session$0.QueryTab.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = db$0.ConnectResult.createFrom;
