// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App exposes backend methods to the frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./internal/db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

export function ActiveConnections(): $CancellablePromise<string[]> {
    return $Call.ByID(3783369028).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Connect(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(164877153, profileID);
}

export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(2457157279, id);
}

export function DescribeTable(profileID: string, schema: string, table: string): $CancellablePromise<db$0.ColumnInfo[]> {
    return $Call.ByID(3867090276, profileID, schema, table).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Disconnect(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(3864343059, profileID);
}

export function ExecuteQuery(profileID: string, sqlStr: string): $CancellablePromise<db$0.QueryResult | null> {
    return $Call.ByID(2868660388, profileID, sqlStr).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetLastActiveProfile returns the profile ID selected last across windows.
 */
export function GetLastActiveProfile(): $CancellablePromise<string> {
    return $Call.ByID(1787524770);
}

export function IsConnected(profileID: string): $CancellablePromise<boolean> {
    return $Call.ByID(236330520, profileID);
}

export function ListDatabases(profileID: string): $CancellablePromise<db$0.DatabaseInfo[]> {
    return $Call.ByID(4238628917, profileID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListIndexes(profileID: string, schema: string, table: string): $CancellablePromise<db$0.IndexInfo[]> {
    return $Call.ByID(3383199879, profileID, schema, table).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListProfiles(): $CancellablePromise<store$0.Profile[]> {
    return $Call.ByID(1957526603).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListSchemas(profileID: string): $CancellablePromise<string[]> {
    return $Call.ByID(3091363483, profileID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListTables(profileID: string, schema: string): $CancellablePromise<db$0.TableInfo[]> {
    return $Call.ByID(364749488, profileID, schema).then(($result: any) => {
        return $$createType12($result);
    });
}

export function RegisteredDrivers(): $CancellablePromise<string[]> {
    return $Call.ByID(3935134584).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveProfile(p: store$0.Profile): $CancellablePromise<store$0.Profile> {
    return $Call.ByID(406053493, p).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * SetLastActiveProfile stores the profile that should be focused by the main window.
 */
export function SetLastActiveProfile(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(3037183246, profileID);
}

export function TestConnection(p: store$0.Profile): $CancellablePromise<db$0.ConnectResult> {
    return $Call.ByID(1257240193, p).then(($result: any) => {
        return $$createType13($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = db$0.ColumnInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = db$0.QueryResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = db$0.DatabaseInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = db$0.IndexInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = store$0.Profile.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = db$0.TableInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = db$0.ConnectResult.createFrom;
