// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {store} from '../models';

export function ActiveConnections():Promise<Array<string>>;

export function Connect(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DescribeTable(arg1:string,arg2:string,arg3:string):Promise<Array<db.ColumnInfo>>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string):Promise<db.QueryResult>;

export function IsConnected(arg1:string):Promise<boolean>;

export function ListDatabases(arg1:string):Promise<Array<db.DatabaseInfo>>;

export function ListIndexes(arg1:string,arg2:string,arg3:string):Promise<Array<db.IndexInfo>>;

export function ListProfiles():Promise<Array<store.Profile>>;

export function ListSchemas(arg1:string):Promise<Array<string>>;

export function ListTables(arg1:string,arg2:string):Promise<Array<db.TableInfo>>;

export function SaveProfile(arg1:store.Profile):Promise<store.Profile>;

export function TestConnection(arg1:store.Profile):Promise<db.ConnectResult>;
