// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is the primary service exposed to the frontend bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./internal/db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * ActiveConnections trả về list profileID đang connected
 */
export function ActiveConnections(): $CancellablePromise<string[]> {
    return $Call.ByID(1375928269).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Connect kết nối theo profileID đã lưu
 */
export function Connect(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(4081416968, profileID);
}

/**
 * DeleteProfile xoá profile và disconnect nếu đang active
 */
export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(1212961758, id);
}

/**
 * DescribeTable trả về columns của 1 table
 */
export function DescribeTable(profileID: string, schema: string, table: string): $CancellablePromise<db$0.ColumnInfo[]> {
    return $Call.ByID(3599051581, profileID, schema, table).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Disconnect đóng connection
 */
export function Disconnect(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(4010927372, profileID);
}

/**
 * ExecuteQuery thực thi raw SQL
 */
export function ExecuteQuery(profileID: string, sqlStr: string): $CancellablePromise<db$0.QueryResult | null> {
    return $Call.ByID(3751584223, profileID, sqlStr).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * IsConnected kiểm tra connection còn sống không
 */
export function IsConnected(profileID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3781091069, profileID);
}

/**
 * ListDatabases trả về tất cả databases (cần connect trước)
 */
export function ListDatabases(profileID: string): $CancellablePromise<db$0.DatabaseInfo[]> {
    return $Call.ByID(3662995272, profileID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListIndexes trả về indexes của 1 table
 */
export function ListIndexes(profileID: string, schema: string, table: string): $CancellablePromise<db$0.IndexInfo[]> {
    return $Call.ByID(1527986762, profileID, schema, table).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListProfiles trả về tất cả profiles (password đã mask)
 */
export function ListProfiles(): $CancellablePromise<store$0.Profile[]> {
    return $Call.ByID(2812097544).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListSchemas trả về tất cả schemas trong database hiện tại
 */
export function ListSchemas(profileID: string): $CancellablePromise<string[]> {
    return $Call.ByID(2599854070, profileID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListTables trả về tables + views trong 1 schema
 */
export function ListTables(profileID: string, schema: string): $CancellablePromise<db$0.TableInfo[]> {
    return $Call.ByID(2978438827, profileID, schema).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * SaveProfile thêm mới hoặc cập nhật profile
 * Truyền profile.ID rỗng để tạo mới, có ID để update
 */
export function SaveProfile(p: store$0.Profile): $CancellablePromise<store$0.Profile> {
    return $Call.ByID(1527812808, p).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * TestConnection thử kết nối mà không lưu vào active connections
 */
export function TestConnection(p: store$0.Profile): $CancellablePromise<db$0.ConnectResult> {
    return $Call.ByID(4037176558, p).then(($result: any) => {
        return $$createType13($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = db$0.ColumnInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = db$0.QueryResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = db$0.DatabaseInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = db$0.IndexInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = store$0.Profile.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = db$0.TableInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = db$0.ConnectResult.createFrom;
