// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ColumnInfo {
    "name": string;
    "dataType": string;
    "isNullable": boolean;
    "isPrimaryKey": boolean;
    "defaultValue": string;
    "position": number;

    /** Creates a new ColumnInfo instance. */
    constructor($$source: Partial<ColumnInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            this["dataType"] = "";
        }
        if (!("isNullable" in $$source)) {
            this["isNullable"] = false;
        }
        if (!("isPrimaryKey" in $$source)) {
            this["isPrimaryKey"] = false;
        }
        if (!("defaultValue" in $$source)) {
            this["defaultValue"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnInfo($$parsedSource as Partial<ColumnInfo>);
    }
}

export class ConnectResult {
    "success": boolean;
    "message": string;
    "version": string;

    /** Creates a new ConnectResult instance. */
    constructor($$source: Partial<ConnectResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectResult($$parsedSource as Partial<ConnectResult>);
    }
}

export class DatabaseInfo {
    "name": string;

    /** Creates a new DatabaseInfo instance. */
    constructor($$source: Partial<DatabaseInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DatabaseInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseInfo($$parsedSource as Partial<DatabaseInfo>);
    }
}

export class IndexInfo {
    "name": string;
    "columns": string[];
    "unique": boolean;

    /** Creates a new IndexInfo instance. */
    constructor($$source: Partial<IndexInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("unique" in $$source)) {
            this["unique"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexInfo {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        return new IndexInfo($$parsedSource as Partial<IndexInfo>);
    }
}

export class QueryResult {
    "columns": string[];
    "rows": any[][];
    "affected": number;
    "duration": number;
    "error": string;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("affected" in $$source)) {
            this["affected"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

export class TableInfo {
    "schema": string;
    "name": string;
    "type": string;

    /** Creates a new TableInfo instance. */
    constructor($$source: Partial<TableInfo> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TableInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableInfo($$parsedSource as Partial<TableInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($$createType1);
